name       : veusz
version    : '3.0'
release    : 7
source     :
    - https://github.com/veusz/veusz/archive/veusz-3.0.tar.gz : d569b3bd62cf7ec2a0164e2c358fc4c28e73bf9478b85731cc6dd63b96ca4905
license    : GPL-2.0-or-later
component  : office.scientific
summary    : A Scientific Plotting and Graphing Program
description: Veusz is a scientific plotting and graphing program with a graphical user interface, designed to produce publication-ready 2D plots.
rundeps    :
    - python3-qt5
    - python3-sip
    - numpy
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5Gui)
    - ghostscript-devel
    - python3-qt5
    - python3-sip-devel
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
    mkdir -p %installroot%/usr/share/{pixmaps,applications}
    install -Dm0644 $workdir/veusz-veusz-$version/icons/veusz.svg $installdir/usr/share/pixmaps/veusz.svg
    install -Dm0644 $workdir/veusz-veusz-$version/support/veusz.desktop $installdir/usr/share/applications/
