name       : veusz
version    : '2.2'
release    : 6
source     :
    - https://github.com/veusz/veusz/archive/veusz-2.2.tar.gz : b78842189e902964863e7f6e3f73b5b39e94e2f9ebdf0c443a140b6c0cdafa24
license    : GPL-2.0
component  : office.scientific
summary    : A Scientific Plotting and Graphing Program
description: Veusz is a scientific plotting and graphing program with a graphical user interface, designed to produce publication-ready 2D plots.
rundeps    :
    - python3-qt5
    - python3-sip
    - numpy
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5Gui)
    - ghostscript-devel
    - python3-qt5
    - python3-sip-devel
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
    mkdir -p %installroot%/usr/share/{pixmaps,applications}
    ln -sfv /usr/lib/python3.5/site-packages/veusz/icons/veusz_64.png %installroot%/usr/share/pixmaps/veusz.png
    cp $pkgfiles/veusz.desktop %installroot%/usr/share/applications/
