name       : veusz
version    : '2.0'
release    : 2
source     :
    - https://github.com/veusz/veusz/archive/veusz-2.0.tar.gz : 812065dde2c6d0577d7fbfaa53c45c7ba76aaf95c0079dc6c5ed6b296dbe7892
license    : GPL-2.0
component  : office.scientific
summary    : A Scientific Plotting and Graphing Program
description:
    Veusz is a scientific plotting and graphing program with a graphical user interface, designed to produce publication-ready 2D plots.
rundeps    :
    - python3-qt5
    - python3-sip
    - numpy
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(Qt5Gui)
    - ghostscript-devel
    - python3-qt5
    - python3-sip-devel
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
    mkdir -p %installroot%/usr/share/{pixmaps,applications}
    ln -sfv /usr/lib/python3.5/site-packages/veusz/icons/veusz_64.png %installroot%/usr/share/pixmaps/veusz.png
    cp $pkgfiles/veusz.desktop %installroot%/usr/share/applications/
